- ""
- "/reviews/laptop-computers"
- "/slideshow_viewer/0,3253,l=311660&a=311035&po=2,00.asp"
- "/article2/0,2817,2419241,00.asp"
- "/news"
- "/article2/0,2817,2418473,00.asp"
- "/category2/0,2806,3076,00.asp"         
- "/27996?OperatingSystem%3dGoogleAndroid3.0orhigher"
- "/article2/0,2817,2417391,00.asp"
- "/business"
- "/category2/0,2806,2352214,00.asp"    
- "/article2/0,2817,2367621,00.asp"
- "/reviews/cell-phones"
- "/current_archive/0,1204,s=1489&t=0,00.asp"
- "/past_archive/0,1204,s=1489&y=2008,00.asp"
- "/products/26635/2"
- "/products/compare/27940?ids=310998,310899,310954"
- "/slideshow/story/311652/test-ss-creation"
- "/slideshow/story/311652/test-ss-creation/1"
- "/slideshow/story/311652/test-ss-creation/3"
- "/slideshow/story/311652/test-ss-creation/seemore"
- "/encyclopedia"
- "/encyclopedia/term/37950/arbitration"
- "/editors-choice/"
- "/category2/0,2806,2358246,00.asp"
- "/reviews/laptop-computers"