# - "http://www.pcmag.com"
# - "http://www.pcmag.com/news"
# - "http://www.pcmag.com/error/pcmag404.asp?404%3b http://www.pcmag.com/encyclopedia_term/0,2542,t=tickler&i=52894,00.asp"
# - "http://www.pcmag.com/reviews/laptop-computers"




- "http://www.nyq.pcmag.com/article/print/:/www.microsoft.com/en-us/download/details.aspx?id=30424"
- "http://www.nyq.pcmag.com/article/print/www.pcmag.com/article/%200,2997,s%253D1470%2526a%"
- "http://www.nyq.pcmag.com/article/print/298137"
- "http://www.nyq.pcmag.com/article/print/4510"
- "http://www.nyq.pcmag.com/article/print/9889929218"
- "http://www.nyq.pcmag.com/article/print/%3Ca%20href="
- "http://www.nyq.pcmag.com/article/print/%3CA%20HREF="
- "http://www.nyq.pcmag.com/article/print/%E2%80%9D- http:/www.tgdaily.com/business-and-law-brief/58403-carol-bartz-to-walk-with-14-million-severance%E2%80%9D"
- "http://www.nyq.pcmag.com/article/print/(- http://googlevideo.blogspot.com/2009/01/turning-down-uploads-at-google-video.html"
- "http://www.nyq.pcmag.com/article/print/www.pulseofthetweeters.com"
- "http://www.nyq.pcmag.com/article/print/www.qualitylogic.com"
- "http://www.nyq.pcmag.com/cgi-local/SoftCart.exe/index.html?L+scstore+bbcp3004ff788878+1365712846"
- "http://www.nyq.pcmag.com/cgi-local/SoftCart.exe/index.html?L+scstore+bbcp3004ff788878+1365858829"
- "http://www.nyq.pcmag.com/cgi-local/SoftCart.exe/index.html?L+scstore+cfjx3595ff163e16+1365666920"
- "http://www.nyq.pcmag.com/cgi-local/SoftCart.exe/index.html?L+scstore+cfjx3595ff163e16+1365724950"
- "http://www.nyq.pcmag.com/cgi-local/SoftCart.exe/index.html?L+scstore+jcbh5000ff2d142d+1365282132"
- "http://www.nyq.pcmag.com/cgi-local/SoftCart.exe/index.html?L+scstore+jcbh5000ff2d142d+1365357881"
- "http://www.nyq.pcmag.com/cgi-local/SoftCart.exe/index.html?L+scstore+zzwq0400ff3cb93c+1365194565"
- "http://www.nyq.pcmag.com/cgi-local/SoftCart.exe/index.html?L+scstore+zzwq0400ff3cb93c+1365240218"
- "http://www.nyq.pcmag.com/article2/0,2817,2418870,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2414462,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2404904,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2403343,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2403255,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2403175,00.asp"
- "http://www.nyq.pcmag.com/slideshow/0,1206,l=&s=27232&a=296717,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2403099,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2397026,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2396889,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2396573,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2396561,00.asp"
- "http://www.nyq.pcmag.com/slideshow/0,1206,l=&s=1594&a=286552,00.asp"
- "http://www.nyq.pcmag.com/slideshow/0,1206,l=&s=1594&a=286342,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2381553,00.asp"
- "http://www.nyq.pcmag.com/slideshow/0,1206,l=&s=27991&a=251929,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2354352,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2354349,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2354346,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2354345,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2354335,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2354334,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2354333,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2354326,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2354314,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2354307,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2354301,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2354300,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2354299,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2354298,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2354295,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2354293,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2354292,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2354291,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2354274,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2354272,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2354270,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2353888,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2342307,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2342305,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2331404,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2327855,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2327097,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2036919,00.asp"

- "http://www.pcmag.com/article2/0,2817,2418870,00.asp"
- "http://www.pcmag.com/article2/0,2817,2414462,00.asp"
- "http://www.pcmag.com/article2/0,2817,2404904,00.asp"
- "http://www.pcmag.com/article2/0,2817,2403343,00.asp"
- "http://www.pcmag.com/article2/0,2817,2403255,00.asp"
- "http://www.pcmag.com/article2/0,2817,2403175,00.asp"
- "http://www.pcmag.com/slideshow/0,1206,l=&s=27232&a=296717,00.asp"
- "http://www.pcmag.com/article2/0,2817,2403099,00.asp"
- "http://www.pcmag.com/article2/0,2817,2397026,00.asp"
- "http://www.pcmag.com/article2/0,2817,2396889,00.asp"
- "http://www.pcmag.com/article2/0,2817,2396573,00.asp"
- "http://www.pcmag.com/article2/0,2817,2396561,00.asp"
- "http://www.pcmag.com/slideshow/0,1206,l=&s=1594&a=286552,00.asp"
- "http://www.pcmag.com/slideshow/0,1206,l=&s=1594&a=286342,00.asp"
- "http://www.pcmag.com/article2/0,2817,2382729,00.asp"
- "http://www.pcmag.com/article2/0,2817,2381553,00.asp"
- "http://www.pcmag.com/slideshow/0,1206,l=&s=27991&a=251929,00.asp"
- "http://www.pcmag.com/article2/0,2817,2354352,00.asp"
- "http://www.pcmag.com/article2/0,2817,2354349,00.asp"
- "http://www.pcmag.com/article2/0,2817,2354346,00.asp"
- "http://www.pcmag.com/article2/0,2817,2354345,00.asp"
- "http://www.pcmag.com/article2/0,2817,2354335,00.asp"
- "http://www.pcmag.com/article2/0,2817,2354334,00.asp"
- "http://www.pcmag.com/article2/0,2817,2354333,00.asp"
- "http://www.pcmag.com/article2/0,2817,2354326,00.asp"
- "http://www.pcmag.com/article2/0,2817,2354314,00.asp"
- "http://www.pcmag.com/article2/0,2817,2354307,00.asp"
- "http://www.pcmag.com/article2/0,2817,2354301,00.asp"
- "http://www.pcmag.com/article2/0,2817,2354300,00.asp"
- "http://www.pcmag.com/article2/0,2817,2354299,00.asp"
- "http://www.pcmag.com/article2/0,2817,2354298,00.asp"
- "http://www.pcmag.com/article2/0,2817,2354295,00.asp"
- "http://www.pcmag.com/article2/0,2817,2354293,00.asp"
- "http://www.pcmag.com/article2/0,2817,2354292,00.asp"
- "http://www.pcmag.com/article2/0,2817,2354291,00.asp"
- "http://www.pcmag.com/article2/0,2817,2354274,00.asp"
- "http://www.pcmag.com/article2/0,2817,2354272,00.asp"
- "http://www.pcmag.com/article2/0,2817,2354270,00.asp"
- "http://www.pcmag.com/article2/0,2817,2353888,00.asp"
- "http://www.pcmag.com/article2/0,2817,2342307,00.asp"
- "http://www.pcmag.com/article2/0,2817,2342305,00.asp"
- "http://www.pcmag.com/article2/0,2817,2331404,00.asp"
- "http://www.pcmag.com/article2/0,2817,2327855,00.asp"
- "http://www.pcmag.com/article2/0,2817,2327097,00.asp"
- "http://www.pcmag.com/article2/0,2817,2036919,00.asp"

- "http://www.nyq.pcmag.com/article2/0,2817,2181834,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2280648,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2286743,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2309774,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2314494,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2317409,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2317412,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2321444,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2322191,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2324203,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2324556,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2324620,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2325559,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2325639,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2325666,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2325685,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2325742,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2325745,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2325754,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2325994,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2325999,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2326329,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2326697,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2326813,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2327450,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2327453,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2328162,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2328163,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2328687,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2328888,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2329924,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2329933,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2330779,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2331757,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2332720,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2332732,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2333168,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2333300,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2334495,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2335512,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2335582,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2336717,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2336819,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2336932,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2337491,00.asp"
- "http://www.nyq.pcmag.com/article2/0,2817,2337762,00.asp"
- "http://nyq.appscout.pcmag.com/video-games/274204-when-the-mortal-kombat-guy-has-too-much-egg-nog"


- "http://www.pcmag.com/article2/0,2817,2122702,00.asp"
- "http://www.pcmag.com/article2/0,2817,2181834,00.asp"
- "http://www.pcmag.com/article2/0,2817,2280648,00.asp"
- "http://www.pcmag.com/article2/0,2817,2286743,00.asp"
- "http://www.pcmag.com/article2/0,2817,2309774,00.asp"
- "http://www.pcmag.com/article2/0,2817,2314494,00.asp"
- "http://www.pcmag.com/article2/0,2817,2317409,00.asp"
- "http://www.pcmag.com/article2/0,2817,2317412,00.asp"
- "http://www.pcmag.com/article2/0,2817,2321444,00.asp"
- "http://www.pcmag.com/article2/0,2817,2322191,00.asp"
- "http://www.pcmag.com/article2/0,2817,2324203,00.asp"
- "http://www.pcmag.com/article2/0,2817,2324556,00.asp"
- "http://www.pcmag.com/article2/0,2817,2324620,00.asp"
- "http://www.pcmag.com/article2/0,2817,2325559,00.asp"
- "http://www.pcmag.com/article2/0,2817,2325639,00.asp"
- "http://www.pcmag.com/article2/0,2817,2325666,00.asp"
- "http://www.pcmag.com/article2/0,2817,2325685,00.asp"
- "http://www.pcmag.com/article2/0,2817,2325742,00.asp"
- "http://www.pcmag.com/article2/0,2817,2325745,00.asp"
- "http://www.pcmag.com/article2/0,2817,2325754,00.asp"
- "http://www.pcmag.com/article2/0,2817,2325994,00.asp"
- "http://www.pcmag.com/article2/0,2817,2325999,00.asp"
- "http://www.pcmag.com/article2/0,2817,2326329,00.asp"
- "http://www.pcmag.com/article2/0,2817,2326697,00.asp"
- "http://www.pcmag.com/article2/0,2817,2326813,00.asp"
- "http://www.pcmag.com/article2/0,2817,2327450,00.asp"
- "http://www.pcmag.com/article2/0,2817,2327453,00.asp"
- "http://www.pcmag.com/article2/0,2817,2328162,00.asp"
- "http://www.pcmag.com/article2/0,2817,2328163,00.asp"
- "http://www.pcmag.com/article2/0,2817,2328687,00.asp"
- "http://www.pcmag.com/article2/0,2817,2328888,00.asp"
- "http://www.pcmag.com/article2/0,2817,2329924,00.asp"
- "http://www.pcmag.com/article2/0,2817,2329933,00.asp"
- "http://www.pcmag.com/article2/0,2817,2330779,00.asp"
- "http://www.pcmag.com/article2/0,2817,2331757,00.asp"
- "http://www.pcmag.com/article2/0,2817,2332720,00.asp"
- "http://www.pcmag.com/article2/0,2817,2332732,00.asp"
- "http://www.pcmag.com/article2/0,2817,2333168,00.asp"
- "http://www.pcmag.com/article2/0,2817,2333300,00.asp"
- "http://www.pcmag.com/article2/0,2817,2334495,00.asp"
- "http://www.pcmag.com/article2/0,2817,2335512,00.asp"
- "http://www.pcmag.com/article2/0,2817,2335582,00.asp"
- "http://www.pcmag.com/article2/0,2817,2336717,00.asp"
- "http://www.pcmag.com/article2/0,2817,2336819,00.asp"
- "http://www.pcmag.com/article2/0,2817,2336932,00.asp"
- "http://www.pcmag.com/article2/0,2817,2337491,00.asp"
- "http://www.pcmag.com/article2/0,2817,2337762,00.asp"
- "http://appscout.pcmag.com/video-games/274204-when-the-mortal-kombat-guy-has-too-much-egg-nog"
